### ISSUE TITLE
Many wallpapers show up as blank

### ISSUE THREAD

**Issue by NayamAmarshe** [saint-13/Linux_Dynamic_Wallpapers#11]
Installed on Gnome 3.38 (ZorinOS) and many wallpapers just show up as blue solid backgrounds. Is there a fix for this?

![image](https://user-images.githubusercontent.com/25067102/153592246-a38dc5c8-2044-4202-8dd8-129cfce13c95.png)

**Comment by amrosolaiman** [comment]
It should be fixed on the repo I forked, try to use that one for now. @saint-13 didn't merge the changes yet.

**Comment by NayamAmarshe** [comment]
> It should be fixed on the repo I forked, try to use that one for now. @saint-13 didn't merge the changes yet.

Yes, thanks. I checked the files and replaced all /home paths with the correct one. It works now :)

**Comment by amrosolaiman** [comment]
have you had to change the paths in the xml files manually or the ones on my fork are working properly now?

**Comment by NayamAmarshe** [comment]
> have you had to change the paths in the xml files manually or the ones on my fork are working properly now?

I did it manually. I noticed that your fork has some invalid paths as well.

**Comment by amrosolaiman** [comment]
> > have you had to change the paths in the xml files manually or the ones on my fork are working properly now?
> 
> I did it manually. I noticed that your fork has some invalid paths as well.

I checked all the xml files but I was unable to find wrong paths. Can you please send me a screenshot or more details so I can fix them?

**Comment by saint-13** [comment]
i merged amrosolaiman pull request. 
but unfortunately i don't have internet access on my Linux machine right now, to check if everything is ok or not.

**Comment by saint-13** [comment]
i tested it. and everything was looking just fine. so i will close this issue.

**Comment by NayamAmarshe** [comment]
> > > have you had to change the paths in the xml files manually or the ones on my fork are working properly now?
> > 
> > 
> > I did it manually. I noticed that your fork has some invalid paths as well.
> 
> I checked all the xml files but I was unable to find wrong paths. Can you please send me a screenshot or more details so I can fix them?

Hi, sorry for the late reply. You're right, It must have been my mistake. I must have cloned the wrong repository as the README.md in your fork still had saint-13's repository link. I apologize for the confusion.
