### ISSUE TITLE
Make a *-git AUR package

### ISSUE THREAD

**Issue by barfin** [saint-13/Linux_Dynamic_Wallpapers#25]
[AUR packages actually exist](https://aur.archlinux.org/packages?O=0&SeB=nd&K=gnome-dynamic-wallpaper&outdated=&SB=p&SO=d&PP=50&submit=Go) but they are broken because they use amirsoleiman's repo and the repo doesn't exist because the account doesn't exist
however even if they get fixed they are still not good
because there is no package to download all of them at once, if you want them all you have to add 56 packages to your system, other than the inconvenience the package maintainer has to add the new wallpapers manually and the user would have no idea that a new wallpaper is available other than actively looking into the repos which I'm sure nobody does or wants to do that
it would be much easier and convenient to make a *-git package in aur that includes all wallpapers for both sides (maintainer and user)

**Comment by saint-13** [comment]
I believe installation process is fairly simple. and honestly, I don't know how to maintain an AUR package!

**Comment by renyuneyun** [comment]
FYI: I have made a AUR package for this.
