### ISSUE TITLE
Instruction under Fedora 36 does not work!

### ISSUE THREAD

**Issue by strykenKN** [saint-13/Linux_Dynamic_Wallpapers#27]
Hello, thanks first of all for the tutorial. 

But unfortunately it doesn't work under Fedora 36, no matter what I click, nothing changes at all, according to the time. It stays with the static image. I have the image with the deer in the mountains and the sunset and the image, no matter what time we have, does not change. I honestly don't know what the problem is. Even if I go into the settings and look at the selected image again, the blue arrow is no longer there, despite taking over the image. And in the top bar as selected image, it also does not appear. It seems to me that Fedora 36 has a big problem here (as unfortunately so often in other areas)

**Comment by saint-13** [comment]
thanks for your feedback.
at the current time I don't have Fedora 36 to test with, in future if find some time to look at fedora 36 I will test this too.

**Comment by saint-13** [comment]
OK, Linux_Dynamic_Wallpapers is not fully compatible with gnome 42. feel free to make it work. currently I'm so pissed off with gnome devs. so I'm trying to stay away from it for while.
