### ISSUE TITLE
Gnome 42 EndeavourOS

### ISSUE THREAD

**Issue by g-lopes** [saint-13/Linux_Dynamic_Wallpapers#29]
First of all, thanks for your work. I really appreciate it.
Second, this software seems not to work under gnome 42. I used the easy_installer script, the files were copied to the correct location `/usr/share/backgrounds/`, but I can't access them from gnome settings.

**Comment by Coeur-Noir** [comment]
Hi,

Did something get copied into `/usr/share/gnome-background-properties` ?

You should also have some .xml file there ( which is just a pointer to the .xml in `/usr/share/backgrounds` )
It's something like
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wallpapers SYSTEM "gnome-wp-list.dtd">
<wallpapers>
 <wallpaper deleted="false">
   <name>name for your slideshow or dynamic wallpaper</name>
   <filename>/path/to/the/file.xml</filename>
   <options>zoom</options>
 </wallpaper>
</wallpapers>
```

**Comment by g-lopes** [comment]
This is the log:
```
Installing wallpapers...
cp: target '/usr/share/gnome-background-properties/': No such file or directory
Dynamic Wallpapers has been installed!
Deleting files used only for the installation process
    |
    '---> Deleted unneeded files!
Now, don't forget to set your preferred dynamic wallpaper from Settings!
```
So I guess tthe files were not copied...

**Comment by Coeur-Noir** [comment]
Mmm… Doesn't EndeavourOS usually make use of Budgie Desktop Environment ?

Asking this, because Budgie DE has removed support for these « dynamic wallpaper » a couple of years ago.

**Comment by saint-13** [comment]
actually i think there is some problems with gnome 42. i don't use gnome 42, I'm still on 41, but tested 42 couple weeks ago and didn't like it. recently gnome devs are ditching lots of functionality from it. they just hate people customize their PERFECT creation, i guess Micro$oft money is made gnome devs
