### ISSUE TITLE
License for the project?

### ISSUE THREAD

**Issue by renyuneyun** [saint-13/Linux_Dynamic_Wallpapers#30]
While making the AUR package, I noticed that this project does not contain a license / copyright description.

For that, I've used `unknown` for now. As suggested [here](https://wiki.archlinux.org/index.php/PKGBUILD#license) ([…] upstream should be contacted about the conditions under which the software is (and is not) available), I'm reaching out to ask if you'd like me to put a specific license in the PKGBUILD?

**Comment by saint-13** [comment]
thank you, there no any specific license.
