### ISSUE TITLE
[ not an issue ] if you like them, get them…

### ISSUE THREAD

**Issue by Coeur-Noir** [saint-13/Linux_Dynamic_Wallpapers#31]
Hi,

sorry am no dev' and don't know how things work on github.

I made some slideshows / dynamic wallpapers for my Ubuntu 22.04.

They are here : https://forum.ubuntu-fr.org/viewtopic.php?pid=22570237#p22570237 and following posts,
with content of their related .xml files.

All pictures processed in Gimp, some were initially made with « trianglify » AppImage, the « wood » picture comes from pixabay ( no license, free for any use, even commercial ), fonts are Ubuntu condensed or Gabriele Font Family ( free for commercial use, also. )

Feel …free to use them : 

⋅ _trianglify_01_ is an abstract design slowly changing color throughout its sequence ( 12 steps ) but not day/night oriented ;
⋅ _wood_ is horizontal wood stripes that change « tone » throughout its sequence, intended for day/night ( the warmer at 12:00, the darker at 00:00 )
⋅ _wood-clock_ is a kind of clock on vertical wood stripes, with a lighter strike that moves according to your time.

Best regards.

**Comment by Coeur-Noir** [comment]
Ok I've tried to import into Github the needed elements, see if you want / like them ;-)
https://github.com/Coeur-Noir/Dynamic-Wallpapers

**Comment by saint-13** [comment]
thank you mate.
