### ISSUE TITLE
On Gnome 42

### ISSUE THREAD

**Issue by shinmendokkodo** [saint-13/Linux_Dynamic_Wallpapers#32]
Hi, I think your install.sh script is having some issues.
When I manually moved the folders and .xml files it is working fine on Gnome 42.
![image](https://user-images.githubusercontent.com/103983186/188666713-fcb8c543-5a71-4b4b-8802-c613c890291a.png)

And thank you for these wallpapers, they are really great.

**Comment by saint-13** [comment]
your welcome, thanks for feedback, yes. install.sh script does not actually copy file on disk, instead it makes virtual link to original files. I can change script but I need some free time to test it.
