### ISSUE TITLE
Is there support for elementaryOS with Pantheon ?

### ISSUE THREAD

**Issue by marwin1991** [saint-13/Linux_Dynamic_Wallpapers#33]
From what I understand there is only support from GNOME 42 and there is no support for elementaryOS with Pantheon ?

**Comment by marwin1991** [comment]
Looks like wallpaper should be set from command line, becasue UI shows:

![Screenshot from 2022-09-15 10 05 47](https://user-images.githubusercontent.com/25181517/190350229-2a0e7ef0-4a75-4695-be5d-8a065430e91c.jpeg)

And when when check the settings:

```
gsettings get org.gnome.desktop.background picture-uri

'file:///usr/share/backgrounds/Dynamic_Wallpapers/Catalina/Catalina-8.jpg'
```

So we need to list files:
```
ls -l /usr/share/backgrounds/Dynamic_Wallpapers/
```

And then set what we want:
```
gsettings set org.gnome.desktop.background picture-uri 'file:///usr/share/backgrounds/Dynamic_Wallpapers/Catalina.xml'
```

**Comment by saint-13** [comment]
Unfortunately, Is there NO support for Elementary OS. because EOS Devs removed all gnome code for xml wallpaper from Pantheon. but i know they are working on something similar and very cool for Pantheon.

**Comment by saint-13** [comment]
> Looks like wallpaper should be set from command line, becasue UI shows:
> 
> ![Screenshot from 2022-09-15 10 05 47](https://user-images.githubusercontent.com/25181517/190350229-2a0e7ef0-4a75-4695-be5d-8a065430e91c.jpeg)
> 
> And when when check the settings:
> 
> ```
> gsettings get org.gnome.desktop.background picture-uri
> ```
> 
> output:
> 
> ```
> 'file:///usr/share/backgrounds/Dynamic_Wallpapers/Catalina/Catalina-8.jpg'
> ```
> 
> So we need to list files:
> 
> ```
> ls -l /usr/share/backgrounds/Dynamic_Wallpapers/
> ```
> 
> And then set what we want:
> 
> ```
> gsettings set org.gnome.desktop.background picture-uri 'file:///usr/share/backgrounds/Dynamic_Wallpapers/Catalina.xml'
> ```

is it working correctly?!!
